#!/usr/bin/env bash

action="${1:-switch}"

if [[ "$action" != "switch" && "$action" != "boot" ]]; then
  echo "Usage: sns [switch|boot]" >&2
  exit 1
fi

nh os "$action" -d always -t "path://$HOME/workspaces/spreadconfig#thinkbook"
