import = [
	"~/.config/alacritty/themes/alacritty-theme/themes/gruvbox_dark.toml"
]
[font]
size = 18

[font.bold]
family = "Terminus (TTF)"
style = "Bold"

[font.bold_italic]
family = "Terminus (TTF)"
style = "Bold Italic"

[font.italic]
family = "Terminus (TTF)"
style = "Italic"

[font.normal]
family = "Terminus (TTF)"
style = "Regular"
