#!/usr/bin/env bash

GIT_AI_AGENT="${GIT_AI_AGENT:-codex}"
GIT_AI_MODEL="${GIT_AI_MODEL:-gpt-5.5}"
GIT_AI_REASONING_EFFORT="${GIT_AI_REASONING_EFFORT:-medium}"
GIT_AI_CODEX_SANDBOX="${GIT_AI_CODEX_SANDBOX:-read-only}"
GIT_AI_CODEX_EPHEMERAL="${GIT_AI_CODEX_EPHEMERAL:-1}"
