#!/usr/bin/env python3
"""Apply the workspace manifest generated by Nix; invoked only by shellHook."""

import fcntl
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import stat
import subprocess
import sys
import tempfile


OWNER = "spreadconfig-workspace"
STATE = ".agent-workspace/state.json"
STORE = ".agent-workspace/store"
FILES = {"AGENTS.md"}
START = "# >>> spreadconfig workspace (managed) >>>"
END = "# <<< spreadconfig workspace (managed) <<<"
NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*\Z")
HASH = re.compile(r"[0-9a-f]{64}\Z")


class ActivationError(Exception):
    pass


def require(condition, message):
    if not condition:
        raise ActivationError(message)


def valid_name(value):
    return isinstance(value, str) and NAME.fullmatch(value) is not None


def path_string(value, label):
    require(isinstance(value, str) and value and "\0" not in value,
            f"{label} must be a nonempty path string")
    return value


def read_json(path):
    def unique(pairs):
        result = {}
        for key, value in pairs:
            require(key not in result, f"duplicate JSON key: {key}")
            result[key] = value
        return result

    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique)


def json_text(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def digest(data):
    return hashlib.sha256(data).hexdigest()


def existing_directory(value, label):
    path = Path(path_string(value, label)).expanduser()
    require(path.is_absolute(), f"{label} must be absolute: {value}")
    path = path.resolve(strict=True)
    require(path.is_dir(), f"{label} is not a directory: {path}")
    return path


def workspace_root():
    def checked(path):
        require(not path.is_relative_to(Path("/nix/store")),
                f"workspace root must not be in the Nix store: {path}")
        require((path / "flake.nix").is_file(),
                f"workspace root must contain flake.nix: {path}")
        return path

    explicit = os.environ.get("SPREADCONFIG_WORKSPACE_ROOT")
    if explicit is not None:
        return checked(existing_directory(explicit, "SPREADCONFIG_WORKSPACE_ROOT"))
    current = Path.cwd().resolve(strict=True)
    for candidate in (current, *current.parents):
        if (candidate / "flake.nix").is_file():
            return checked(candidate)
    raise ActivationError("no flake.nix above the current directory; set "
                          "SPREADCONFIG_WORKSPACE_ROOT explicitly")


def relative_skill_path(value):
    path_string(value, "relativePath")
    path = PurePosixPath(value)
    require(not path.is_absolute() and "\\" not in value
            and all(part not in ("", ".", "..") for part in value.split("/")),
            f"unsafe skill relativePath: {value}")
    return path


def check_skill(source, name):
    path = source / "SKILL.md"
    require(source.is_dir() and path.is_file(),
            f"skill source needs a SKILL.md file: {source}")
    lines = path.read_text(encoding="utf-8").splitlines()
    require(lines and lines[0] == "---", f"missing skill frontmatter: {path}")
    try:
        end = lines.index("---", 1)
    except ValueError:
        raise ActivationError(f"unterminated skill frontmatter: {path}") from None
    names = [line for line in lines[1:end] if line.startswith("name:")]
    require(len(names) == 1, f"skill needs one frontmatter name: {path}")
    match = re.fullmatch(r'''name:\s*(?:"([^"\n]+)"|'([^'\n]+)'|([^\s#'"\n]+))\s*(?:#.*)?''', names[0])
    require(match is not None, f"invalid skill frontmatter name: {path}")
    declared = next(group for group in match.groups() if group is not None)
    require(declared == name, f"skill name mismatch: requested {name}, declared {declared} in {path}")


def prepare(manifest):
    require(isinstance(manifest, dict), "manifest must be an object")
    required = {"schemaVersion", "skills", "claude", "instructions", "storeRoot"}
    require(set(manifest) == required, "unexpected or missing manifest fields")
    require(type(manifest["schemaVersion"]) is int and manifest["schemaVersion"] == 2,
            "unsupported manifest schemaVersion")
    require(type(manifest["claude"]) is bool, "claude must be a boolean")
    require(isinstance(manifest["skills"], list), "skills must be a list")
    require(isinstance(manifest["instructions"], str), "instructions must be a string")
    bundle = existing_directory(manifest["storeRoot"], "storeRoot")
    source_root = None

    links = {STORE: str(bundle)}
    names = set()
    for skill in manifest["skills"]:
        require(isinstance(skill, dict) and set(skill) in
                ({"name", "source"}, {"name", "relativePath"}),
                "each skill needs name and exactly one of source or relativePath")
        name = skill["name"]
        require(valid_name(name), f"unsafe skill name: {name!r}")
        require(name not in names, f"duplicate skill name: {name}")
        names.add(name)
        if "relativePath" in skill:
            relative = relative_skill_path(skill["relativePath"])
            if source_root is None:
                value = os.environ.get("SPREADCONFIG_SOURCE_ROOT")
                require(value is not None, "local skills require SPREADCONFIG_SOURCE_ROOT; "
                        "there is no store fallback")
                source_root = existing_directory(value, "SPREADCONFIG_SOURCE_ROOT")
            source = (source_root / relative).resolve(strict=True)
            require(source.is_relative_to(source_root),
                    f"local skill escapes SPREADCONFIG_SOURCE_ROOT: {relative}")
        else:
            # Keep the precise fixed path selected by Nix, regardless of the
            # local checkout environment or any symlinks inside the store.
            source = Path(path_string(skill["source"], f"source for {name}"))
            require(source.is_absolute(), f"source for {name} must be absolute")
        check_skill(source, name)
        links[f".agents/skills/{name}"] = str(source)
        if manifest["claude"]:
            links[f".claude/skills/{name}"] = f"../../.agents/skills/{name}"
    if manifest["claude"]:
        links["CLAUDE.md"] = "AGENTS.md"

    agents = (
        "# Workspace Instructions\n\n"
        "Skills are available under `.agents/skills`.\n"
    )
    if manifest["instructions"]:
        agents += "\n" + manifest["instructions"].rstrip() + "\n"
    return links, {"AGENTS.md": agents.encode()}


def no_symlink_parents(root, relative):
    path = root
    for part in PurePosixPath(relative).parts[:-1]:
        path /= part
        if path.is_symlink():
            raise ActivationError(f"refusing symlinked output directory: {path}")
        if path.exists():
            require(path.is_dir(), f"output parent is not a directory: {path}")


def regular_file(path):
    return path.exists() and stat.S_ISREG(path.lstat().st_mode)


def exists(path):
    return os.path.lexists(path)


def valid_owned_link(path, target):
    if not isinstance(path, str) or not isinstance(target, str) or "\0" in target:
        return False
    if path == STORE:
        return Path(target).is_absolute()
    if path == "CLAUDE.md":
        return target == "AGENTS.md"
    for client in (".agents", ".claude"):
        prefix = f"{client}/skills/"
        if path.startswith(prefix) and valid_name(path[len(prefix):]):
            return (Path(target).is_absolute() if client == ".agents"
                    else target == f"../../.agents/skills/{path[len(prefix):]}")
    return False


def read_state(root):
    no_symlink_parents(root, STATE)
    path = root / STATE
    if not exists(path):
        return None
    require(regular_file(path), f"state must be a regular file, not a symlink: {path}")
    state = read_json(path)
    require(isinstance(state, dict) and set(state) ==
            {"schemaVersion", "owner", "links", "files", "gitignoreBlock"},
            "invalid workspace state structure")
    require(type(state["schemaVersion"]) is int and state["schemaVersion"] == 2,
            "unsupported workspace state schemaVersion")
    require(state["owner"] == OWNER, "unrecognized workspace state owner")
    require(isinstance(state["links"], dict)
            and all(valid_owned_link(path, target) for path, target in state["links"].items())
            and STORE in state["links"], "unsafe owned links in workspace state")
    require(isinstance(state["files"], dict) and set(state["files"]) == FILES
            and all(isinstance(value, str) and HASH.fullmatch(value)
                    for value in state["files"].values()), "unsafe owned files in workspace state")
    require(state["gitignoreBlock"] == ignore_block(state["links"]),
            "invalid managed gitignore block in workspace state")
    return state


def ignore_block(links):
    paths = {"/.agent-workspace/", "/AGENTS.md"}
    paths.update("/" + path for path in links if path != STORE)
    return START + "\n" + "\n".join(sorted(paths)) + "\n" + END + "\n"


def prepare_gitignore(root, old, links):
    path = root / ".gitignore"
    if exists(path):
        require(regular_file(path), f".gitignore must be a regular file: {path}")
        text = path.read_bytes().decode("utf-8")
    else:
        text = ""
    lines = text.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if line.rstrip("\r\n") == START]
    ends = [i for i, line in enumerate(lines) if line.rstrip("\r\n") == END]
    block = ignore_block(links)
    if starts or ends:
        require(len(starts) == len(ends) == 1 and starts[0] < ends[0],
                "malformed managed block in .gitignore")
        current = "".join(lines[starts[0]:ends[0] + 1])
        require(old is not None and current == old["gitignoreBlock"],
                "managed .gitignore block is not owned or was edited")
        return ("".join(lines[:starts[0]]) + block + "".join(lines[ends[0] + 1:])).encode(), block
    require(old is None or not exists(path), "managed .gitignore block was removed")
    separator = "" if not text or text.endswith("\n") else "\n"
    return (text + separator + block).encode(), block


def preflight(root, old, links, files):
    old_links = old["links"] if old else {}
    old_files = old["files"] if old else {}
    for relative in sorted(set(links) | set(files) | set(old_links) | set(old_files)):
        no_symlink_parents(root, relative)
        path = root / relative
        if not exists(path):
            continue
        if relative in old_links:
            require(path.is_symlink() and os.readlink(path) == old_links[relative],
                    f"owned link was replaced or edited: {path}")
        elif relative in old_files:
            require(regular_file(path) and digest(path.read_bytes()) == old_files[relative],
                    f"generated file was replaced or edited: {path}")
        else:
            raise ActivationError(f"refusing to overwrite an unowned path: {path}")
    return prepare_gitignore(root, old, links)


def atomic_file(path, data, mode=None):
    if regular_file(path) and path.read_bytes() == data:
        return
    if mode is None:
        mode = stat.S_IMODE(path.stat().st_mode) if regular_file(path) else 0o644
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".workspace-", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fchmod(stream.fileno(), mode)
        os.replace(temporary, path)
    finally:
        if os.path.lexists(temporary):
            os.unlink(temporary)


def atomic_link(path, target):
    if path.is_symlink() and os.readlink(path) == target:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".workspace-", dir=path.parent)
    os.close(fd)
    os.unlink(temporary)
    try:
        os.symlink(target, temporary)
        os.replace(temporary, path)
    finally:
        if os.path.lexists(temporary):
            os.unlink(temporary)


def activate(manifest, root):
    # Lock the directory itself so the first activation needs no preflight writes.
    descriptor = os.open(root, os.O_RDONLY | os.O_DIRECTORY)
    try:
        fcntl.flock(descriptor, fcntl.LOCK_EX)
        links, files = prepare(manifest)
        old = read_state(root)
        gitignore, block = preflight(root, old, links, files)

        # Register already-built assets before changing client links. Plain store
        # symlinks do not survive GC; registration must also refresh after a move.
        (root / ".agent-workspace").mkdir(exist_ok=True)
        subprocess.run(["nix-store", "--add-root", str(root / STORE), "--indirect",
                        "--realise", links[STORE]], check=True, stdout=subprocess.DEVNULL,
                       timeout=60)
        require((root / STORE).is_symlink() and os.readlink(root / STORE) == links[STORE],
                "nix-store did not create the expected GC root")
        for relative in sorted((set(old["links"]) if old else set()) - set(links)):
            path = root / relative
            if exists(path):
                path.unlink()
        for relative, target in sorted(links.items()):
            if relative != STORE:
                atomic_link(root / relative, target)
        for relative, data in files.items():
            atomic_file(root / relative, data)
        atomic_file(root / ".gitignore", gitignore)
        state = {"schemaVersion": 2, "owner": OWNER, "links": links,
                 "files": {path: digest(data) for path, data in files.items()},
                 "gitignoreBlock": block}
        atomic_file(root / STATE, json_text(state).encode(), mode=0o600)
    finally:
        os.close(descriptor)


def main():
    try:
        require(len(sys.argv) == 2, "expected the Nix-generated manifest path")
        root = workspace_root()
        activate(read_json(Path(sys.argv[1])), root)
        # shellHook captures this to export the actual root, even from a subdir.
        print(root)
        return 0
    except (ActivationError, OSError, ValueError, RuntimeError,
            subprocess.SubprocessError) as error:
        print(f"workspace activation: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
