{
  host,
  lib,
  projDir,
  ...
}:

let
  capabilityString = value: if value == null then "unknown" else lib.boolToString value;
  devices = host.profile.home.devices;
  shellContext = {
    SPREADCONFIG_CONFIGURED_HOST = host.name;
    SPREADCONFIG_CONFIGURED_REPO = projDir;
    SPREADCONFIG_CAMERA_DEVICE = if devices.camera == null then "" else devices.camera;
    SPREADCONFIG_BATTERY_DEVICE = if devices.battery == null then "" else devices.battery;
    SPREADCONFIG_BACKLIGHT_DEVICE = if devices.backlight == null then "" else devices.backlight;
    SPREADCONFIG_HAS_BATTERY = capabilityString host.capabilities.battery;
    SPREADCONFIG_HAS_BACKLIGHT = capabilityString host.capabilities.backlight;
  };
in
{
  xdg.configFile."spreadconfig/host.sh".text = ''
    # Generated by Home Manager from the host declaration.
    ${lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "${name}=${lib.escapeShellArg value}") shellContext
    )}
  '';
}
