#!/usr/bin/env bash

action="${1:-boot}"

if [[ "$action" != "switch" && "$action" != "boot" ]]; then
  echo "Usage: nix_clean_boot_entries [switch|boot]" >&2
  exit 1
fi

sns_until "$action"
sudo nix-env --delete-generations old --profile /nix/var/nix/profiles/system
sns_until "$action"
sudo nix-env --delete-generations old --profile /nix/var/nix/profiles/system
