#!/usr/bin/env bash
set -euo pipefail

action="${1:-switch}"

if [[ "$action" != "switch" && "$action" != "boot" ]]; then
  echo "Usage: sfull [switch|boot]" >&2
  exit 1
fi

sns_until "$action"
hms_until
