#!/usr/bin/env bash

LOG_DIR="/home/spreadzhao/.local/share/net-log"
QUERY_SCRIPT="$SCRIPT_HOME/util/net-usage-query.sh"

CURRENT_BOOT_ID=$(cat /proc/sys/kernel/random/boot_id)

if [ "$1" = "list" ]; then
    "$QUERY_SCRIPT" list
    exit $?
fi

if [ -z "$1" ]; then
    latest=$(
        find "$LOG_DIR" \
            -maxdepth 1 \
            -type f \
            -name "*__${CURRENT_BOOT_ID}.log" \
            -printf "%T@|%p\n" 2>/dev/null |
        sort -nr |
        head -n1 |
        cut -d'|' -f2-
    )

    if [ -z "$latest" ]; then
        echo "No log file found for current boot_id: $CURRENT_BOOT_ID"
        exit 1
    fi

    target="$(basename "$latest")"
else
    target="$1"
fi

"$QUERY_SCRIPT" "$target" | \
jq '.processes |= map(select(.upload_bytes >= 1073741824 or .download_bytes >= 1073741824))'
# "$QUERY_SCRIPT" "$target" | jq
